services:
  app:
    build: .
    container_name: python-server-blog
    command: gunicorn --bind 0.0.0.0:5000 -w 4 run:app
    ports:
      - 5000:5000
      - 5678:5678
    volumes:
      - .:/code
    depends_on:
      - redis
  redis:
    image: redis:alpine